# Project information
site_name: 'Storelocatorjs'
site_description: 'Storelocatorjs is a fast and lightweight Javascript library for build your own customizable store locator with a minimalist theme. The cloud function is included to handle store filter requests.'
site_author: 'Joris DANIEL aka Yoriiis'
site_url: 'https://yoriiis.github.io/storelocatorjs/'
repo_name: 'yoriiis/storelocatorjs'
repo_url: 'https://github.com/yoriiis/storelocatorjs'
use_directory_urls: false

# Pages
nav:
  - Overview: 'index.md'
  - Getting started: 'getting-started.md'
  - How it works: 'how-it-works.md'
  - Available options: 'available-options.md'
  - Features: 'features.md'
  - Demo: 'demo.html'
  - Download: 'download.md'
  - Licenses: 'licenses.md'

# Copyright
copyright: 'Copyright &copy; 2021 - Joris DANIEL aka Yoriiis'

# Documentation and theme
theme:
  name: 'material'
  custom_dir: 'docs/theme'
  language: 'en'
  palette:
    primary: 'white'
    accent: 'white'
  font:
    text: 'Roboto'
    code: 'Ubuntu Mono'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.details
  - meta
